---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-fallback-service
  namespace: food2gether
  labels:
    app: api-fallback-service
spec:
  selector:
    matchLabels:
      app: api-fallback-service
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  api-fallback-service
      labels:
        app: api-fallback-service
    spec:
      containers:
      - name: api-fallback-service
        image: ghcr.io/food2gether/api-fallback-service:0.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env: []
        ports:
        - containerPort: 8080
          name: http
      restartPolicy: Always
