name: Verify push to protected branch

on:
  push:
    branches:
      - main

jobs:
  protected-push:
    uses: food2gether/workflows/.github/workflows/backend-protected-push.yml@main
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}