name: Verify Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pull-request:
    uses: food2gether/workflows/.github/workflows/backend-pull-request.yaml@main
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}